"""empty message

Revision ID: 12236d6228a8
Revises: 6beae10a3790
Create Date: 2017-04-10 07:14:26.787496

"""

# revision identifiers, used by Alembic.
revision = '12236d6228a8'
down_revision = '6beae10a3790'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constraintanalysis', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'constraintanalysis', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'constraintanalysis', type_='foreignkey')
    op.drop_column('constraintanalysis', 'section_id')
    # ### end Alembic commands ###
