"""empty message

Revision ID: 2b30b28053ff
Revises: e7f2a5f4b2af
Create Date: 2017-04-12 09:32:32.764352

"""

# revision identifiers, used by Alembic.
revision = '2b30b28053ff'
down_revision = 'e7f2a5f4b2af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_constraintanalysis_projid_reportid_section', 'constraintanalysis', ['project_id', 'reportingdate_id', 'section_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_constraintanalysis_projid_reportid_section', 'constraintanalysis', type_='unique')
    # ### end Alembic commands ###
