"""empty message

Revision ID: 47f3a207d89a
Revises: 12236d6228a8
Create Date: 2017-04-10 09:58:06.951191

"""

# revision identifiers, used by Alembic.
revision = '47f3a207d89a'
down_revision = '12236d6228a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookaheads', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lookaheads', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lookaheads', type_='foreignkey')
    op.drop_column('lookaheads', 'section_id')
    # ### end Alembic commands ###
