"""empty message

Revision ID: 6beae10a3790
Revises: 985f84e41a78
Create Date: 2017-04-07 12:17:51.353797

"""

# revision identifiers, used by Alembic.
revision = '6beae10a3790'
down_revision = '985f84e41a78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraintanalysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('reportingdate_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reportingdate_id'], ['reportingdates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraintanalysis_details',
    sa.Column('constraintanalysis_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('constraint_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['constraint_id'], ['constraints.id'], ),
    sa.ForeignKeyConstraint(['constraintanalysis_id'], ['constraintanalysis.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['lookaheads_details.id'], ),
    sa.PrimaryKeyConstraint('constraintanalysis_id', 'task_id', 'constraint_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('constraintanalysis_details')
    op.drop_table('constraintanalysis')
    # ### end Alembic commands ###
