"""empty message

Revision ID: c38e20537271
Revises: aa6bd35f7c87
Create Date: 2017-04-12 10:43:49.988389

"""

# revision identifiers, used by Alembic.
revision = 'c38e20537271'
down_revision = 'aa6bd35f7c87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_1_lookahead_details_lookahead_id_task_code', 'lookaheads_details', ['lookahead_id', 'task_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1_lookahead_details_lookahead_id_task_code', 'lookaheads_details', type_='unique')
    # ### end Alembic commands ###
