"""empty message

Revision ID: dd7577f9939d
Revises: 47f3a207d89a
Create Date: 2017-04-10 14:57:43.354078

"""

# revision identifiers, used by Alembic.
revision = 'dd7577f9939d'
down_revision = '47f3a207d89a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constraintanalysis_details', sa.Column('can_do', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constraintanalysis_details', 'can_do')
    # ### end Alembic commands ###
