"""empty message

Revision ID: e659d2671dc8
Revises: None
Create Date: 2017-04-12 11:29:08.788211

"""

# revision identifiers, used by Alembic.
revision = 'e659d2671dc8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_constraintanalysis_projid_reportid_section', 'constraintanalysis', ['project_id', 'reportingdate_id', 'section_id'])
    op.create_unique_constraint('uix_1', 'lookaheads', ['project_id', 'reportingdate_id', 'section_id'])
    op.create_unique_constraint('uix_1_lookahead_details_lookahead_id_task_code', 'lookaheads_details', ['lookahead_id', 'task_code'])
    op.create_unique_constraint('uix_1', 'user_project', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'user_project', type_='unique')
    op.drop_constraint('uix_1_lookahead_details_lookahead_id_task_code', 'lookaheads_details', type_='unique')
    op.drop_constraint('uix_1', 'lookaheads', type_='unique')
    op.drop_constraint('uix_constraintanalysis_projid_reportid_section', 'constraintanalysis', type_='unique')
    # ### end Alembic commands ###
