"""empty message

Revision ID: fe4855cc93a7
Revises: 9f00a5849e88
Create Date: 2017-06-09 09:00:03.546084

"""

# revision identifiers, used by Alembic.
revision = 'fe4855cc93a7'
down_revision = '9f00a5849e88'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constraintanalysis_details', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constraintanalysis_details', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
